base_url = "http://localhost:1234/v1"
model = "openai/gpt-oss-20b"
big_model = "openai/gpt-oss-120b"
unthinking = "meta/llama-3.3-70b"
embedding_model = "text-embedding-embeddinggemma-300m-qat"
api_key = "local"